name: "Create PDF"

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write

jobs:
  main:
    if: github.event.issue.title == 'start'
    runs-on: ubuntu-latest

    env:
      CV_FILE_PATH: cv.yaml

    steps:
      - name: Close the issue
        run: |
          curl -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
          -d '{"state":"closed"}'

      - uses: "actions/checkout@v4"

      - name: Decrypt ${{ env.CV_FILE_PATH }}
        run: |
          openssl enc -aes-256-cbc -d \
          -in ${{ env.CV_FILE_PATH }}.enc \
          -out ${{ env.CV_FILE_PATH }} \
          -pass "pass:${{ secrets.ENCRYPTION_KEY }}"

      - name: Create PDF
        run: |
          pip install "rendercv[full]" \
          && rendercv render ${{ env.CV_FILE_PATH }} -o output -nomd -nohtml -nopng -notypst

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: output
          retention-days: 1
