name: Delete workflow

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "run_id"
        required: true
        type: string

permissions:
  actions: write

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - run: |
          curl -L \
          -X DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.inputs.run_id }}