name: Encrypt cv.yaml

on:
  push:
    paths:
      - cv.yaml

permissions:
  actions: write
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest

    env:
      CV_FILE_PATH: cv.yaml

    steps:
    - uses: actions/checkout@v4

    - name: Install OpenSSL
      run: sudo apt-get install -y openssl

    - name: Encrypt ${{ env.CV_FILE_PATH }}
      run: |
        openssl enc -aes-256-cbc -salt \
        -in ${{ env.CV_FILE_PATH }} \
        -out ${{ env.CV_FILE_PATH }}.enc \
        -pass "pass:${{ secrets.ENCRYPTION_KEY }}"

    - name: Replace original file with encrypted file
      run: rm ${{ env.CV_FILE_PATH }}

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Amend the last commit with the encrypted file
      run: |
        git add .
        git commit --amend -m "Update ${{ env.CV_FILE_PATH}}"
      
    - name: Force push changes
      run: |
        git push origin master --force

    - name : Delete this workflow
      if: always()
      run: |
        curl -L \
        -X POST \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${{ github.repository }}/actions/workflows/delete-workflow.yml/dispatches \
        -d '{"ref":"master", "inputs":{"run_id": "${{ github.run_id }}"}}'